/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M22
 * Generated at: 2017-07-29 08:06:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.products.ProductDbUtil;
import java.util.List;
import com.products.product;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1500426170000L));
    _jspx_dependants.put("jar:file:/C:/Users/Jiaqihuang/Desktop/bdproj/bulldog/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/bulldog/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323287178000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.products.product");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.products.ProductDbUtil");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<!--[if lt IE 7]><html class=\"no-js lt-ie9 lt-ie8 lt-ie7\" lang=\"en\"> <![endif]-->\r\n");
      out.write("<!--[if IE 7]><html class=\"no-js lt-ie9 lt-ie8\" lang=\"en\"> <![endif]-->\r\n");
      out.write("<!--[if IE 8]><html class=\"no-js lt-ie9\" lang=\"en\"> <![endif]-->\r\n");
      out.write("<!--[if IE 9 ]><html class=\"ie9 no-js\"> <![endif]-->\r\n");
      out.write("<!--[if (gt IE 9)|!(IE)]><!--> <html class=\"no-js\"> <!--<![endif]-->\r\n");
      out.write("<head>\r\n");
      out.write("\r\n");
      out.write("  <!-- Basic page needs ================================================== -->\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\">\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <link rel=\"shortcut icon\" href=\"//cdn.shopify.com/s/files/1/0720/4459/files/favicon_32x32.png?v=1480350603\" type=\"image/png\" />\r\n");
      out.write("  <!-- Latest compiled and minified CSS -->\r\n");
      out.write("\r\n");
      out.write("  <!-- Title and description ================================================== -->\r\n");
      out.write("  <title>\r\n");
      out.write("  Bliss - Pop Theme by Shopify\r\n");
      out.write("  </title>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <!-- Social meta ================================================== -->\r\n");
      out.write("  \r\n");
      out.write("<meta property=\"og:site_name\" content=\"Pop Theme by Shopify\">\r\n");
      out.write("<!-- Index -->\r\n");
      out.write("\r\n");
      out.write("  <meta property=\"og:type\" content=\"website\">\r\n");
      out.write("  <meta property=\"og:title\" content=\"Bliss - Pop Theme by Shopify\">\r\n");
      out.write("  \r\n");
      out.write("    <meta property=\"og:description\" content=\"\">\r\n");
      out.write("  \r\n");
      out.write("<!-- Product  -->\r\n");
      out.write("\r\n");
      out.write(" \r\n");
      out.write("  <!-- Helpers ================================================== -->\r\n");
      out.write("<!--   <link rel=\"canonical\" href=\"https://poptheme-bone-promo.myshopify.com/\">\r\n");
      out.write(" -->  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("    <!-- Ajaxify Cart Plugin ================================================== -->\r\n");
      out.write("    <link href=\"/jiaqi/css/ajaxify.scss.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  <!-- CSS ================================================== -->\r\n");
      out.write("  <link href=\"/jiaqi/css/timber.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("  <link href=\"//fonts.googleapis.com/css?family=Raleway:500,800\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("\r\n");
      out.write("   <link rel=\"stylesheet\" type=\"text/css\" href=\"main.css\">\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <script>\r\n");
      out.write("    window.theme = window.theme || {};\r\n");
      out.write("    \r\n");
      out.write("    var theme = {\r\n");
      out.write("      moneyFormat: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${{amount}}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\",\r\n");
      out.write("      cartType: 'drawer'\r\n");
      out.write("    }\r\n");
      out.write("  </script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Header hook for plugins ================================================== -->\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<!--[if lt IE 9]>\r\n");
      out.write("<script src=\"//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("<script src=\"//cdn.shopify.com/s/files/1/0720/4459/t/4/assets/respond.min.js?16771221820700569719\" type=\"text/javascript\"></script>\r\n");
      out.write("<link href=\"//cdn.shopify.com/s/files/1/0720/4459/t/4/assets/respond-proxy.html\" id=\"respond-proxy\" rel=\"respond-proxy\" />\r\n");
      out.write("<link href=\"//poptheme-bone-promo.myshopify.com/search?q=69a98cef8dfa76c0a0cbf0c42d3215db\" id=\"respond-redirect\" rel=\"respond-redirect\" />\r\n");
      out.write("<script src=\"//poptheme-bone-promo.myshopify.com/search?q=69a98cef8dfa76c0a0cbf0c42d3215db\" type=\"text/javascript\"></script>\r\n");
      out.write("<![endif]-->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  <!--[if (gt IE 9)|!(IE)]><!--><script src=\"//cdn.shopify.com/s/files/1/0720/4459/t/4/assets/theme.js?16771221820700569719\" defer=\"defer\"></script><!--<![endif]-->\r\n");
      out.write("  <!--[if lte IE 9]><script src=\"//cdn.shopify.com/s/files/1/0720/4459/t/4/assets/theme.js?16771221820700569719\"></script><![endif]-->\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"//ajax.googleapis.com/ajax/libs/jquery/2.2.3/jquery.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  <script src=\"/jiaqi/js/modernizr.min.js\" type=\"text/javascript\"></script>\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<h1 style=\"z-index:20;\">sdhjskfhsdhs</h1>\r\n");
      out.write("<body id=\"bliss-pop-theme-by-shopify\" class=\"template-index\" >\r\n");
      out.write("\r\n");
      out.write("  <div id=\"shopify-section-header\" class=\"shopify-section\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".site-header {\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("@media screen and (max-width: 1024px) {\r\n");
      out.write("  .site-header {\r\n");
      out.write("    height: 70px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("@media screen and (min-width: 1025px) {\r\n");
      out.write("  .main-content {\r\n");
      out.write("    margin: 90px 0 0 0;\r\n");
      out.write("  }\r\n");
      out.write("  .site-header {\r\n");
      out.write("    height: 100%;\r\n");
      out.write("    width: 250px;\r\n");
      out.write("    overflow-y: auto;\r\n");
      out.write("    left: 0;\r\n");
      out.write("    position: fixed;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write(".nav-mobile {\r\n");
      out.write("  width: 250px;\r\n");
      out.write("}\r\n");
      out.write(".page-move--nav .page-element {\r\n");
      out.write("  left: 250px;\r\n");
      out.write("}\r\n");
      out.write("@media screen and (min-width: 1025px) {\r\n");
      out.write("  .page-wrapper {\r\n");
      out.write("    left: 250px;\r\n");
      out.write("    width: calc(100% - 250px);\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write(".supports-csstransforms .page-move--nav .page-element {\r\n");
      out.write("  left: 0;\r\n");
      out.write("  -webkit-transform: translateX(250px);\r\n");
      out.write("  -moz-transform: translateX(250px);\r\n");
      out.write("  -ms-transform: translateX(250px);\r\n");
      out.write("  -o-transform: translateX(250px);\r\n");
      out.write("  transform: translateX(250px);\r\n");
      out.write("}\r\n");
      out.write("@media screen and (min-width: 1025px) {\r\n");
      out.write("  .supports-csstransforms .page-move--cart .page-element {\r\n");
      out.write("    left: calc(250px / 2);\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("@media screen and (max-width: 1024px) {\r\n");
      out.write("  .page-wrapper {\r\n");
      out.write("    top: 70px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write(".page-move--nav .ajaxify-drawer {\r\n");
      out.write("  right: -250px;\r\n");
      out.write("}\r\n");
      out.write(".supports-csstransforms .page-move--nav .ajaxify-drawer {\r\n");
      out.write("  right: 0;\r\n");
      out.write("  -webkit-transform: translateX(250px);\r\n");
      out.write("  -moz-transform: translateX(250px);\r\n");
      out.write("  -ms-transform: translateX(250px);\r\n");
      out.write("  -o-transform: translateX(250px);\r\n");
      out.write("  transform: translateX(250px);\r\n");
      out.write("}\r\n");
      out.write("@media screen and (max-width: 1024px) {\r\n");
      out.write("  .header-logo img {\r\n");
      out.write("    max-height: 40px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("@media screen and (min-width: 1025px) {\r\n");
      out.write("  .header-logo img {\r\n");
      out.write("    max-height: none;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write(".nav-bar {\r\n");
      out.write("  height: 70px;\r\n");
      out.write("}\r\n");
      out.write("@media screen and (max-width: 1024px) {\r\n");
      out.write("  .cart-toggle,\r\n");
      out.write("  .nav-toggle {\r\n");
      out.write("    height: 70px;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"nav-mobile\">\r\n");
      out.write("  <nav class=\"nav-bar\" role=\"navigation\">\r\n");
      out.write("    <div class=\"wrapper\">\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul class=\"site-nav\" id=\"accessibleNav\">     \r\n");
      out.write("        <li class=\"dropdown\" style=\"padding:10px;\">\r\n");
      out.write("        <a href=\"#\" style=\"font-size:18px;\" class=\"dropdown-toggle text-info\" data-toggle=\"dropdown\">Sign In<b class=\"caret\"></b></a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <form id=\"signin\" class=\"navbar-form navbar-left\" role=\"form\" action=\"login\" method=\"post\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("      \t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span>\r\n");
      out.write("      \t\t\t\t\t\t<input id=\"email\" type=\"text\" class=\"form-control\" name=\"email\" placeholder=\"Email or user name\">\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("   \t\t\t \t\t\t<div class=\"input-group\">\r\n");
      out.write("      \t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\"></i></span>\r\n");
      out.write("      \t\t\t\t\t\t<input id=\"password\" type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"Password\">\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t<br>      <hr class=\"hr\">\r\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-primary\" value=\"log in\"/>\r\n");
      out.write("                         </form>\r\n");
      out.write("                        </ul>\r\n");
      out.write("        </li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<ul class=\"site-nav\" id=\"accessibleNav\">     \r\n");
      out.write("        <li class=\"dropdown\" style=\"padding:10px;\">\r\n");
      out.write("            <a href=\"#\" style=\"font-size:18px;\" class=\"dropdown-toggle text-info\" data-toggle=\"dropdown\">Sign Up<b class=\"caret\"></b></a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <form id=\"signin\" class=\"navbar-form navbar-left\" role=\"form\" action=\"register\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("      \t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-envelope\"></i></span>\r\n");
      out.write("      \t\t\t\t\t\t<input id=\"email\" type=\"text\" class=\"form-control\" name=\"contact\" placeholder=\"Email\">\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("      \t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span>\r\n");
      out.write("      \t\t\t\t\t\t<input id=\"user\" type=\"text\" class=\"form-control\" name=\"username\" placeholder=\"user name\">\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("   \t\t\t \t\t\t<div class=\"input-group\">\r\n");
      out.write("      \t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\"></i></span>\r\n");
      out.write("      \t\t\t\t\t\t<input id=\"password\" type=\"password\" class=\"form-control\" name=\"pin\" placeholder=\"Password\">\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<br>      <hr class=\"hr\">\r\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-primary\" value=\"sign up\"/>\r\n");
      out.write("                         </form>\r\n");
      out.write("                        </ul>\r\n");
      out.write("          </li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </nav>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<header class=\"site-header page-element\" role=\"banner\" data-section-id=\"header\" data-section-type=\"header\">\r\n");
      out.write("\r\n");
      out.write("  <div class=\"nav-bar grid--full large--hide\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"grid-item one-quarter\">\r\n");
      out.write("      <button type=\"button\" class=\"text-link nav-toggle\" id=\"navToggle\">\r\n");
      out.write("        <div class=\"table-contain\">\r\n");
      out.write("          <div class=\"table-contain__inner\">\r\n");
      out.write("            <span class=\"icon-fallback-text\">\r\n");
      out.write("              <span class=\"icon icon-hamburger\" aria-hidden=\"true\"></span>\r\n");
      out.write("              <span class=\"fallback-text\">Menu</span>\r\n");
      out.write("            </span>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("      </button>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"grid-item two-quarters\">\r\n");
      out.write("\r\n");
      out.write("      <div class=\"table-contain\">\r\n");
      out.write("        <div class=\"table-contain__inner\">\r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("          <h1 class=\"header-logo\" itemscope itemtype=\"http://schema.org/Organization\">\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("          <a href=\"/\" itemprop=\"url\">\r\n");
      out.write("            <img src=\"//cdn.shopify.com/s/files/1/0720/4459/files/logo_450x.png?v=1494273851\" alt=\"Pop Theme by Shopify\" itemprop=\"logo\">\r\n");
      out.write("          </a>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("          </h1>\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("<!--  nknow cart area -->\r\n");
      out.write("     <div class=\"grid-item one-quarter\"> \r\n");
      out.write("      <a href=\"/cart\" class=\"cart-toggle\">\r\n");
      out.write("      <div class=\"table-contain\">\r\n");
      out.write("        <div class=\"table-contain__inner\">\r\n");
      out.write("          <span class=\"icon-fallback-text\">\r\n");
      out.write("            <span class=\"icon icon-cart\" aria-hidden=\"true\"></span>\r\n");
      out.write("            <span class=\"fallback-text\">Cart</span>\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </a>  \r\n");
      out.write("    </div>\r\n");
      out.write("    <!--  nknow cart area -->\r\n");
      out.write("    \r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"grid--full\">\r\n");
      out.write("      <div class=\"grid-item medium-down--hide\">\r\n");
      out.write("      \r\n");
      out.write("        <h1 class=\"header-logo\" itemscope itemtype=\"http://schema.org/Organization\">\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("        <a href=\"/\" itemprop=\"url\">\r\n");
      out.write("          <img src=\"//cdn.shopify.com/s/files/1/0720/4459/files/logo_450x.png?v=1494273851\" alt=\"Pop Theme by Shopify\" itemprop=\"logo\">\r\n");
      out.write("        </a>\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("        </h1>\r\n");
      out.write("      \r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("    <div class=\"medium-down--hide\">\r\n");
      out.write("     <ul class=\"site-nav\">\r\n");
      out.write("<form action=\"/search\" method=\"get\" class=\"input-group search-bar\" role=\"search\">\r\n");
      out.write("  \r\n");
      out.write("  <input type=\"search\" name=\"q\" value=\"\" placeholder=\"Search our store\" class=\"input-group-field\" aria-label=\"Search our store\">\r\n");
      out.write("  <span class=\"input-group-btn\">\r\n");
      out.write("    <button type=\"submit\" class=\"btn icon-fallback-text\">\r\n");
      out.write("      <span class=\"icon icon-search\" aria-hidden=\"true\"></span>\r\n");
      out.write("      <span class=\"fallback-text\">Search</span>\r\n");
      out.write("    </button>\r\n");
      out.write("  </span>\r\n");
      out.write("</form>\r\n");
      out.write("        \r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <hr class=\"hr--small\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"medium-down--hide\">\r\n");
      out.write("      <ul class=\"site-nav\">\r\n");
      out.write("        <li>\r\n");
      out.write("          <a href=\"/cart\" class=\"cart-toggle site-nav__link\">\r\n");
      out.write("            <span class=\"icon icon-cart\" aria-hidden=\"true\"></span>\r\n");
      out.write("            Cart\r\n");
      out.write("            <span id=\"cartCount\" class=\"hidden-count\">(0)</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </li>\r\n");
      out.write("        \r\n");
      out.write("      </ul>\r\n");
      out.write("\r\n");
      out.write("      <hr class=\"hr--small\">\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("<nav class=\"medium-down--hide\" role=\"navigation\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul class=\"site-nav\" id=\"accessibleNav\">\r\n");
      out.write("<li class=\"dropdown\">\r\n");
      out.write("            <a href=\"#\" style=\"font-size:16px;\" class=\"dropdown-toggle text-info\" data-toggle=\"dropdown\">Sign In<b class=\"caret\"></b></a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <form id=\"signin\" class=\"navbar-form navbar-left\" role=\"form\" action=\"login\" method=\"post\">\r\n");
      out.write("                        <div class=\"input-group\">\r\n");
      out.write("      \t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span>\r\n");
      out.write("      \t\t\t\t\t\t<input id=\"email\" type=\"text\" class=\"form-control\" name=\"email\" placeholder=\"Email or user name\">\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("   \t\t\t \t\t\t<div class=\"input-group\">\r\n");
      out.write("      \t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\"></i></span>\r\n");
      out.write("      \t\t\t\t\t\t<input id=\"password\" type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"Password\">\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t<br>      <hr class=\"hr\">\r\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-primary\" value=\"log in\"/>\r\n");
      out.write("                         </form>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("      <hr class=\"hr--small\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<ul class=\"site-nav\" id=\"accessibleNav\">\r\n");
      out.write(" <li class=\"dropdown\">\r\n");
      out.write("            <a href=\"#\" style=\"font-size:16px;\" class=\"dropdown-toggle text-info\" data-toggle=\"dropdown\">Sign Up<b class=\"caret\"></b></a>\r\n");
      out.write("                        <ul class=\"dropdown-menu\">\r\n");
      out.write("                        <form id=\"signin\" class=\"navbar-form navbar-left\" role=\"form\" action=\"register\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("      \t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-envelope\"></i></span>\r\n");
      out.write("      \t\t\t\t\t\t<input id=\"email\" type=\"text\" class=\"form-control\" name=\"contact\" placeholder=\"Email\">\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t<div class=\"input-group\">\r\n");
      out.write("      \t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-user\"></i></span>\r\n");
      out.write("      \t\t\t\t\t\t<input id=\"user\" type=\"text\" class=\"form-control\" name=\"username\" placeholder=\"user name\">\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("   \t\t\t \t\t\t<div class=\"input-group\">\r\n");
      out.write("      \t\t\t\t\t\t<span class=\"input-group-addon\"><i class=\"glyphicon glyphicon-lock\"></i></span>\r\n");
      out.write("      \t\t\t\t\t\t<input id=\"password\" type=\"password\" class=\"form-control\" name=\"pin\" placeholder=\"Password\">\r\n");
      out.write("    \t\t\t\t\t</div>\r\n");
      out.write("    \t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t<br>      <hr class=\"hr\">\r\n");
      out.write("                        <input type=\"submit\" class=\"btn btn-primary\" value=\"sign up\" />\r\n");
      out.write("                         </form>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </li>\r\n");
      out.write("</ul>\r\n");
      out.write("     \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </nav>\r\n");
      out.write("\r\n");
      out.write("  </div>\r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("  <div class=\"page-wrapper page-element\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!-- top navgation bar -->  \r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".topnav {\r\n");
      out.write("  overflow: hidden;\r\n");
      out.write("  background-color: #fff;\r\n");
      out.write("}\r\n");
      out.write(".topnav a {\r\n");
      out.write("  float: left;\r\n");
      out.write("  display: block;\r\n");
      out.write("  color: black;\r\n");
      out.write("  text-align: center;\r\n");
      out.write("  padding: 14px 16px;\r\n");
      out.write("  text-decoration: none;\r\n");
      out.write("  font-size: 17px;\r\n");
      out.write("}\r\n");
      out.write(".topnav a:hover {\r\n");
      out.write("  background-color: #ddd;\r\n");
      out.write("  color: black;\r\n");
      out.write("}\r\n");
      out.write(".topnav .active {\r\n");
      out.write("    background-color: orange;\r\n");
      out.write("    color: white;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("  <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- .................................................... -->   \r\n");
      out.write("    \r\n");
      out.write("<div class=\"nav-bar grid--full large--hide\">\r\n");
      out.write("<form action=\"/search\" method=\"get\" class=\"input-group search-bar\" role=\"search\">\r\n");
      out.write("  \r\n");
      out.write("  <input type=\"search\" name=\"q\" value=\"\" placeholder=\"Search our store\" class=\"input-group-field\" aria-label=\"Search our store\">\r\n");
      out.write("  <span class=\"input-group-btn\">\r\n");
      out.write("    <button type=\"submit\" class=\"btn icon-fallback-text\">\r\n");
      out.write("      <span class=\"icon icon-search\" aria-hidden=\"true\"></span>\r\n");
      out.write("      <span class=\"fallback-text\">Search</span>\r\n");
      out.write("    </button>\r\n");
      out.write("  </span>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("    <main class=\"main-content\" role=\"main\">\r\n");
      out.write("      <div class=\"wrapper\">\r\n");
      out.write("\r\n");
      out.write("        <!-- BEGIN content_for_index --><div id=\"shopify-section-slideshow\" class=\"shopify-section index-section\">\r\n");
      out.write("  \r\n");
      out.write("  <div class=\"flexslider\" id=\"flexslider--slideshow\" data-section-id=\"slideshow\" data-section-type=\"slideshow-section\" data-autoplay=\"true\" data-speed=\"5000\" data-animation-type=\"slide\">\r\n");
      out.write("    <ul class=\"slides\">\r\n");
      out.write("\r\n");
      out.write("      \r\n");
      out.write("        \r\n");
      out.write("          <li id=\"slide--slideshow-0\" data-flexslider-index=\"0\" >\r\n");
      out.write("            <a href=\"/collections/all\" class=\"slide-link\">\r\n");
      out.write("              <img src=\"//cdn.shopify.com/s/files/1/0720/4459/files/slide_1_1060x.jpg?v=1494273814\" alt=\"A young woman looking into the mirror while applying makeup\" />\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("      \r\n");
      out.write("        \r\n");
      out.write("          <li id=\"slide--slideshow-1\" data-flexslider-index=\"1\" >\r\n");
      out.write("            <a href=\"/collections/all\" class=\"slide-link\">\r\n");
      out.write("              <img src=\"//cdn.shopify.com/s/files/1/0720/4459/files/slide_2_1060x.jpg?v=1494273833\" alt=\"Perfume bottles on a table with rose petals\" />\r\n");
      out.write("            </a>\r\n");
      out.write("          </li>\r\n");
      out.write("          \r\n");
      out.write("      \r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div><div id=\"shopify-section-featured-collection\" class=\"shopify-section index-section\"><style>\r\n");
      out.write("@media screen and (min-width: 769px) {\r\n");
      out.write("  [data-section-id=\"featured-collection\"] .product__details {\r\n");
      out.write("    \r\n");
      out.write("      margin-top: 15px;\r\n");
      out.write("    \r\n");
      out.write("    z-index: 2;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("  [data-section-id=\"featured-collection\"] .product__price {\r\n");
      out.write("    margin-bottom: 0;\r\n");
      out.write("  }\r\n");
      out.write("  @include at-query($min, $large) {\r\n");
      out.write("    .product:hover .product__price {\r\n");
      out.write("      color: #d14800;\r\n");
      out.write("    }\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div data-section-id=\"featured-collection\">\r\n");
      out.write("  <div class=\"section-header text-center\">\r\n");
      out.write("    \r\n");
      out.write("      <h2 class=\"section-header--title\">Featured Products</h2>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("<!-- product grid begin -->\r\n");
      out.write("<!--  assume in server, get all product information and saved in to a arraylist: request.setAttribute(\"prods\",prod_list);-->\r\n");
      out.write("\r\n");
      out.write(" <div class=\"grid-uniform product-grid\">\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write(" <!-- product frid end -->\r\n");
      out.write("      \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div><div id=\"shopify-section-1480350289228\" class=\"shopify-section index-section\"><div class=\"grid\">\r\n");
      out.write("  \r\n");
      out.write("  \r\n");
      out.write("</div>\r\n");
      out.write("</div><!-- END content_for_index -->\r\n");
      out.write("      </div>\r\n");
      out.write("      <div id=\"shopify-section-footer\" class=\"shopify-section\">\r\n");
      out.write("<style>\r\n");
      out.write(".site-footer {\r\n");
      out.write("  padding: 0 0 30px;\r\n");
      out.write("  \r\n");
      out.write("}\r\n");
      out.write("@media screen and (min-width: 1025px) {\r\n");
      out.write("  .site-footer {\r\n");
      out.write("    \r\n");
      out.write("    padding: 60px 0;\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<footer class=\"site-footer small--text-center medium--text-center\" role=\"contentinfo\">\r\n");
      out.write("  <!-- <div class=\"wrapper\">\r\n");
      out.write("    <hr class=\"hr--clear large--hide\">\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      <div class=\"grid\">\r\n");
      out.write("      \r\n");
      out.write("        \r\n");
      out.write("          <div class=\"grid-item large--two-thirds\">\r\n");
      out.write("        \r\n");
      out.write("        \r\n");
      out.write("          <h3 class=\"h5 onboarding-header\">About us</h3>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"rte\">\r\n");
      out.write("          <p>Pop is a responsive Shopify theme. This is a demo shop for the theme store and comes in two&nbsp;different styles which you can find on the Theme Store.</p>\r\n");
      out.write("<p>Store location</p>\r\n");
      out.write("<p>123 Blueberry Avenue, Blueberry ON., M6K 1Y3</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("          </div>\r\n");
      out.write("        \r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("        \r\n");
      out.write("          <div class=\"grid-item large--one-third\">\r\n");
      out.write("        \r\n");
      out.write("          <hr class=\"hr--clear large--hide\">\r\n");
      out.write("          <h3 class=\"h5\">Get Connected</h3>\r\n");
      out.write("          \r\n");
      out.write("            <div class=\"grid\">\r\n");
      out.write("              <div class=\"grid-item medium--two-thirds push--medium--one-sixth\">\r\n");
      out.write("                <label class=\"form-label--hidden\">\r\n");
      out.write("  <span class=\"visuallyhidden\">Enter your email</span>\r\n");
      out.write("</label>\r\n");
      out.write("  <div class=\"form-vertical\">\r\n");
      out.write("    <form method=\"post\" action=\"https://poptheme-bone-promo.myshopify.com/contact#contact_form\" id=\"contact_form\" class=\"contact-form\" accept-charset=\"UTF-8\"><input type=\"hidden\" value=\"customer\" name=\"form_type\" /><input type=\"hidden\" name=\"utf8\" value=\"â\" />\r\n");
      out.write("      \r\n");
      out.write("      \r\n");
      out.write("        <input type=\"hidden\" name=\"contact[tags]\" value=\"newsletter\">\r\n");
      out.write("        <div class=\"input-group\">\r\n");
      out.write("          <input type=\"email\" value=\"\" placeholder=\"email@example.com\" name=\"contact[email]\" id=\"Email\" class=\"input-group-field\" aria-label=\"email@example.com\" autocorrect=\"off\" autocapitalize=\"off\">\r\n");
      out.write("          <span class=\"input-group-btn\">\r\n");
      out.write("            <button type=\"submit\" class=\"btn icon-fallback-text\" name=\"commit\" id=\"subscribe\">\r\n");
      out.write("              <span class=\"icon icon-chevron-right\" aria-hidden=\"true\"></span>\r\n");
      out.write("              <span class=\"fallback-text\">Subscribe</span>\r\n");
      out.write("            </button>\r\n");
      out.write("          </span>\r\n");
      out.write("        </div>\r\n");
      out.write("      \r\n");
      out.write("    </form>\r\n");
      out.write("  </div>\r\n");
      out.write("              </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          \r\n");
      out.write("          \r\n");
      out.write("            \r\n");
      out.write("            <ul class=\"inline-list social-icons\">\r\n");
      out.write("              \r\n");
      out.write("                <li>\r\n");
      out.write("                  <a class=\"icon-fallback-text\" href=\"https://twitter.com/shopify\" title=\"Pop Theme by Shopify on Twitter\">\r\n");
      out.write("                    <span class=\"icon icon-twitter\" aria-hidden=\"true\"></span>\r\n");
      out.write("                    <span class=\"fallback-text\">Twitter</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("                <li>\r\n");
      out.write("                  <a class=\"icon-fallback-text\" href=\"https://www.facebook.com/shopify\" title=\"Pop Theme by Shopify on Facebook\">\r\n");
      out.write("                    <span class=\"icon icon-facebook\" aria-hidden=\"true\"></span>\r\n");
      out.write("                    <span class=\"fallback-text\">Facebook</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("                <li>\r\n");
      out.write("                  <a class=\"icon-fallback-text\" href=\"https://www.pinterest.com/shopify/\" title=\"Pop Theme by Shopify on Pinterest\">\r\n");
      out.write("                    <span class=\"icon icon-pinterest\" aria-hidden=\"true\"></span>\r\n");
      out.write("                    <span class=\"fallback-text\">Pinterest</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("                <li>\r\n");
      out.write("                  <a class=\"icon-fallback-text\" href=\"https://instagram.com/shopify/\" title=\"Pop Theme by Shopify on Instagram\">\r\n");
      out.write("                    <span class=\"icon icon-instagram\" aria-hidden=\"true\"></span>\r\n");
      out.write("                    <span class=\"fallback-text\">Instagram</span>\r\n");
      out.write("                  </a>\r\n");
      out.write("                </li>\r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("              \r\n");
      out.write("            </ul>\r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("          </div>\r\n");
      out.write("        \r\n");
      out.write("      \r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("    <hr class=\"hr--clear\">\r\n");
      out.write("    \r\n");
      out.write("      <div class=\"grid\">\r\n");
      out.write("        <div class=\"grid-item medium--two-thirds push--medium--one-sixth large--one-half push--large--one-quarter nav-search\">\r\n");
      out.write("          <h3 class=\"h5 text-center\">Search for products on our site</h3>\r\n");
      out.write("          \r\n");
      out.write("<label class=\"form-label--hidden\">\r\n");
      out.write("  <span class=\"visuallyhidden\">Search our store</span>\r\n");
      out.write("</label>\r\n");
      out.write("<form action=\"/search\" method=\"get\" class=\"input-group search-bar\" role=\"search\">\r\n");
      out.write("  \r\n");
      out.write("  <input type=\"search\" name=\"q\" value=\"\" placeholder=\"Search our store\" class=\"input-group-field\" aria-label=\"Search our store\">\r\n");
      out.write("  <span class=\"input-group-btn\">\r\n");
      out.write("    <button type=\"submit\" class=\"btn icon-fallback-text\">\r\n");
      out.write("      <span class=\"icon icon-search\" aria-hidden=\"true\"></span>\r\n");
      out.write("      <span class=\"fallback-text\">Search</span>\r\n");
      out.write("    </button>\r\n");
      out.write("  </span>\r\n");
      out.write("</form>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"text-center\">\r\n");
      out.write("      \r\n");
      out.write("        <ul class=\"inline-list nav-secondary\">\r\n");
      out.write("          \r\n");
      out.write("            <li><a href=\"/search\">Search</a></li>\r\n");
      out.write("          \r\n");
      out.write("            <li><a href=\"/pages/about-us\">About Us</a></li>\r\n");
      out.write("          \r\n");
      out.write("            <li><a href=\"/pages/contact-us\">Contact Us</a></li>\r\n");
      out.write("          \r\n");
      out.write("        </ul>\r\n");
      out.write("      \r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      \r\n");
      out.write("      <ul class=\"inline-list payment-icons text-center\">\r\n");
      out.write("        \r\n");
      out.write("          \r\n");
      out.write("            <li>\r\n");
      out.write("              <span class=\"icon-fallback-text\">\r\n");
      out.write("                <span class=\"icon icon-visa\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"fallback-text\">visa</span>\r\n");
      out.write("              </span>\r\n");
      out.write("            </li>\r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("          \r\n");
      out.write("            <li>\r\n");
      out.write("              <span class=\"icon-fallback-text\">\r\n");
      out.write("                <span class=\"icon icon-master\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"fallback-text\">master</span>\r\n");
      out.write("              </span>\r\n");
      out.write("            </li>\r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("          \r\n");
      out.write("            <li>\r\n");
      out.write("              <span class=\"icon-fallback-text\">\r\n");
      out.write("                <span class=\"icon icon-american_express\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"fallback-text\">american express</span>\r\n");
      out.write("              </span>\r\n");
      out.write("            </li>\r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("          \r\n");
      out.write("            <li>\r\n");
      out.write("              <span class=\"icon-fallback-text\">\r\n");
      out.write("                <span class=\"icon icon-paypal\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"fallback-text\">paypal</span>\r\n");
      out.write("              </span>\r\n");
      out.write("            </li>\r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("          \r\n");
      out.write("            <li>\r\n");
      out.write("              <span class=\"icon-fallback-text\">\r\n");
      out.write("                <span class=\"icon icon-diners_club\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"fallback-text\">diners club</span>\r\n");
      out.write("              </span>\r\n");
      out.write("            </li>\r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("          \r\n");
      out.write("            <li>\r\n");
      out.write("              <span class=\"icon-fallback-text\">\r\n");
      out.write("                <span class=\"icon icon-discover\" aria-hidden=\"true\"></span>\r\n");
      out.write("                <span class=\"fallback-text\">discover</span>\r\n");
      out.write("              </span>\r\n");
      out.write("            </li>\r\n");
      out.write("          \r\n");
      out.write("        \r\n");
      out.write("      </ul>\r\n");
      out.write("    \r\n");
      out.write("    <div class=\"text-center\">\r\n");
      out.write("      <small>\r\n");
      out.write("        Copyright &copy; 2017 <a href=\"/\" title=\"\">Pop Theme by Shopify</a> | <a target=\"_blank\" rel=\"nofollow\" href=\"https://www.shopify.com\">Powered by Shopify</a><br>\r\n");
      out.write("      </small>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</footer> -->\r\n");
      out.write("</div>\r\n");
      out.write("    </main>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("      <script src=\"//cdn.shopify.com/s/files/1/0720/4459/t/4/assets/handlebars.min.js?16771221820700569719\" type=\"text/javascript\"></script>\r\n");
      out.write("      \r\n");
      out.write("  <script id=\"cartTemplate\" type=\"text/template\">\r\n");
      out.write("  \r\n");
      out.write("  </script>\r\n");
      out.write("  <script id=\"drawerTemplate\" type=\"text/template\">\r\n");
      out.write("  \r\n");
      out.write("  </script>\r\n");
      out.write("  <script id=\"modalTemplate\" type=\"text/template\">\r\n");
      out.write("  \r\n");
      out.write("  </script>\r\n");
      out.write("  <script id=\"ajaxifyQty\" type=\"text/template\">\r\n");
      out.write("  \r\n");
      out.write("  </script>\r\n");
      out.write("  <script id=\"jsQty\" type=\"text/template\">\r\n");
      out.write("  \r\n");
      out.write("  </script>\r\n");
      out.write("<!--  cart detail-->\r\n");
      out.write("      <script src=\"//cdn.shopify.com/s/files/1/0720/4459/t/4/assets/ajaxify.js?16771221820700569719\" type=\"text/javascript\"></script>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("  </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /home.jsp(562,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("tempProduct");
      // /home.jsp(562,0) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/home.jsp(562,0) '${PRODUCT_LIST}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${PRODUCT_LIST}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("     \r\n");
            out.write("\t<div class=\"grid-item medium--one-third large--one-third\" >\r\n");
            out.write("\t        <!-- snippets/product-grid-item.liquid -->\r\n");
            out.write("\t<div class=\" on-sale\">\r\n");
            out.write("\t  <div class=\"product-wrapper\">\r\n");
            out.write("\t    <a href=\"/products/perfumeoil-garden\" class=\"product\">\r\n");
            out.write("\t      \r\n");
            out.write("\t        <img src=\"");
            if (_jspx_meth_c_005furl_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\"alt=\"Perfume Oil- Garden\" class=\"product__img\">\r\n");
            out.write("\t      \r\n");
            out.write("\t      <div class=\"product__cover\"></div>\r\n");
            out.write("\t      \r\n");
            out.write("\t\r\n");
            out.write("\t      <div class=\"product__details text-center\">\r\n");
            out.write("\t        <div class=\"table-contain\">\r\n");
            out.write("\t          <div class=\"table-contain__inner\">\r\n");
            out.write("\t            <p class=\"h4 product__title\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tempProduct.getName()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</p>\r\n");
            out.write("\t            <p class=\"product__price\">\r\n");
            out.write("\t              \r\n");
            out.write("\t                <span class=\"visuallyhidden\">Sale price: </span>\r\n");
            out.write("\t              \r\n");
            out.write("\t              \r\n");
            out.write("\t              ");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tempProduct.getPrice()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\r\n");
            out.write("\t              \r\n");
            out.write("\t              \r\n");
            out.write("\t            </p>\r\n");
            out.write("\t          </div>\r\n");
            out.write("\t        </div>\r\n");
            out.write("\t      </div>\r\n");
            out.write("\t    \r\n");
            out.write("\t    \r\n");
            out.write("\t      <div class=\"on-sale-tag text-center\">\r\n");
            out.write("\t        <span class=\"tag\" aria-hidden=\"true\">Sale</span>\r\n");
            out.write("\t      </div>\r\n");
            out.write("\t    \r\n");
            out.write("\t    </a>\r\n");
            out.write("\t  </div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\t\r\n");
            out.write("\t</div>\r\n");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /home.jsp(569,19) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${tempProduct.getImageurl()}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
